config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => '/attachinary'

  devise_for :users

  constraints lambda { |req| (req.subdomains - ['build']).any? } do
    root to: 'websites#show'
    get 'edit', to: 'websites#edit', as: 'edit_own_website'
    patch '/', to: 'websites#update', as: 'own_website'
    get 'events', to: 'pages#events'
  end

  constraints subdomain: 'build' do
    root to: 'pages#home'
    resources :websites, only: [:new, :create, :edit, :update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :title, presence: true
  validates :city, presence: true
  validates :address, presence: true
  validates :begin_at, presence: true
  validates :end_at, presence: true
end

app/models/template.rb
class Template < ApplicationRecord
  has_many :websites

  validates :name, presence: true
  validates :slug, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_one :website

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/website.rb
class Website < ApplicationRecord
  RESERVED_KEYWORDS = ['build']

  before_create :set_default

  belongs_to :user
  belongs_to :template

  has_attachment :background_image
  has_attachment :profile_image
  has_attachment :banner_background

  validate do
    errors.add 'URL is a reserved keyword' if url.to_s.in? RESERVED_KEYWORDS
  end

  def host(domain: ENV['APPLICATION_DOMAIN'])
    'http://' + [url, domain].join('.')
  end

  private

  def set_default
    self.title = 'Dorothée'
    self.description = 'After making my beginnings at the theater, I was successful thanks to television in the 80s-90s where I was found on Recré A2 and Le Club Dorothée. Otherwise I love to sing and my real name is Frédérique Hoschedé.'
    self.facebook_url = 'dorothee'
    self.twitter_url = '@dorothee'
    self.email = 'dorothee@gmail.com'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  layout :layout

  attr_reader :current_tenant

  def layout
    if devise_controller?
      'devise'
    else
      'application'
    end
  end

  private

  def set_tenant
    @current_tenant = request.subdomains.first
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_tenant, only: [:events]
  skip_before_action :authenticate_user!, only: [:home, :events]

  def home
  end

  def events
    @events = Event.all
    @website = Website.find_by(url: current_tenant)
  end
end

app/controllers/templates_controller.rb
class TemplatesController < ApplicationController
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_tenant, only: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: :show

  layout 'builder', only: [:edit]

  def index
    @websites = [current_user.website]
  end

  def show
    @website = Website.find_by_url(current_tenant)
  end

  def edit
    @templates = Template.all
    @website = current_user.website if current_user.website&.url == current_tenant || current_user.website&.id == params[:id].to_i
    @url = case current_tenant
           when 'build' then website_path(@website)
           else '/'
           end
  end

  def update
    @website = current_user.website if current_user.website&.url == current_tenant || current_user.website&.id == params[:id].to_i
    @template = Template.find(params[:website][:template_id])
    @website.template = @template
    @website.update(website_params)

    respond_to do |format|
      format.html { redirect_to @website.host }
      format.js
    end
  end

  def create
    @website = Website.create!(user: current_user, template: Template.first)
    redirect_to edit_website_path @website
  end

  # GET /websites/:id/template => { template: ":template_slug"}
  def template
    @website = Website.find(params[:id])
    template_slug = params[:template_slug]
    template_html = render_to_string partial: "templates/#{template_slug}", website: @website
    render json: { html: template_html }.to_json
  end

  private

  def website_params
    params.require(:website).permit(
      :template_id,
      :title,
      :description,
      :background_image,
      :profile_image,
      :facebook_url,
      :twitter_url,
      :email,
      :url,
      :banner_title,
      :banner_cta,
      :banner_punchline,
      :banner_background,
      :color_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(text)
    content_for :title, text
  end

  def cl_image_path_or_default(image, options = {})
    if image
      cl_image_path image.path, options
    else
      'https://res.cloudinary.com/dy4rog9h0/image/upload/v1511951967/qnudk7b6khwivnairedi.jpg'
    end
  end

  def cl_image_tag_or_default(image, options = {})
    if image
      cl_image_tag image.path, options
    else
      image_tag 'https://res.cloudinary.com/dy4rog9h0/image/upload/v1511953517/dorothee_yusfkt.png', options
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/meta' %>
    <title>
      <%= if content_for?(:title) then yield(:title) end %>
    </title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body onload="changeCouleur()">
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/layouts/builder.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/meta' %>
    <title>Construisez votre site web</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="" id="structure_sheet">
    <link rel="stylesheet" href="" id="style_sheet">
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Connectez-vous</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <div class="devise-wrapper">
      <%= render 'shared/navbar' %>
      <%= render 'shared/flashes' %>
      <div class="container">
        <div class="row">
          <div class="col-sm-6 col-sm-offset-3">
            <div class="devise-content">
              <%= yield %>
              <%= javascript_include_tag 'application' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/events.html.erb
<link rel="stylesheet" href="<%= asset_path("layouts/#{ @website.template.slug }") %>" id="structure_sheet">
<link rel="stylesheet" href="<%= @website.color_id %>" id="style_sheet">

<div class="website-background">
  <div class="container">

    <h1>Agenda</h1>

    <% @events.each do |event| %>
      <div class="event-card">
        <h2><%= event.title %></h2>
        <h3><%= event.city %></h3>
        <hr>
        <p><b><%= event.address %></b></p>
        <div class="event-dates">
          <%= event.begin_at %>
          <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
          <%= event.end_at %>
        </div>
        <%= link_to "En savoir plus", "http://www.riberac-tourisme.com/fr/agenda/#{event.title.parameterize}.html?idProduit=#{event.sirtaqui_id}", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<% title("Hébergeurs du pays ribéracquois bienvenue !") %>

<%= render 'shared/navbar' %>
<%= render 'shared/banner' %>
<%= render 'shared/process' %>


<div class="container cards-title">
  <h2>Besoin d'aide? Des questions?</h2>
</div>

<div class="cards-wrapper">
  <div class="container" style="display: flex; align-items: center; justify-content: center; height: 100%;">
    <h2 style="padding: 0 50px;">L'office de tourisme se tient à votre disposition pour vous accompagner dans la création de votre site.</h2>
    <%= image_tag 'office-de-tourisme.jpg', size: '300x300' %>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>Mettez vous en avant facilement et en quelques clics</h1>
    <p class="intro">Créez votre site web personnalisé en quelques minutes.</p>
    <% if current_user %>
      <% if website = current_user.website %>
        <% if website.url.present? %>
          <%= link_to 'Personnaliser mon site', edit_own_website_url(host: website.host), class: 'button' %></li>
        <% else %>
          <%= link_to 'Personnaliser mon site', edit_website_url(website), class: 'button' %></li>
        <% end %>
      <% else %>
        <%= button_to 'Créer mon site', websites_path, method: :post, class: 'button' %>
      <% end %>
    <% else %>
      <%= link_to 'Créer mon site', new_user_session_path, class: 'button' %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-content">
    <h2>Prêts à attaquer?</h2>
    <% if current_user %>
      <% if website = current_user.website %>
        <% if website.url.present? %>
          <%= link_to 'Personnaliser mon site', edit_own_website_url(host: website.host), class: 'link' %></li>
        <% else %>
          <%= link_to 'Personnaliser mon site', edit_website_url(website), class: 'link' %></li>
        <% end %>
      <% else %>
        <%= button_to 'Créer mon site', websites_path, method: :post, class: 'button' %>
      <% end %>
    <% else %>
      <%= link_to 'Créer mon site', new_user_session_path, class: 'button' %>
    <% end %>
  </div>
</div>

app/views/shared/_meta.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="The easiest way to create your online presence for free, in few minutes.">
<meta property="og:title" content="Hop your website without technical skills">
<meta property="og:image" content="https://i.imgur.com/ywkVqLa.jpg">
<meta property="og:description" content="Hop is the easiest way to create your online presence for free, in few minutes.">
<meta property="og:site_name" content="Hop"/>
<meta property="og:type" content="website" />
<meta property="og:url" content="https://www.apphop.io" />
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@HopWebsite">
<meta name="twitter:title" content="Hop your website without technical skills">
<meta name="twitter:description" content="Hop is the easiest way to create your online presence for free, in few minutes.">
<meta name="twitter:creator" content="@HopWebsite">
<meta name="twitter:image:src" content="og.jpg">

app/views/shared/_navbar.html.erb
<div class="navbar-home">
  <%= link_to root_path do %>
    <%= image_tag 'logo.png' %>
  <% end %>

  <ul>
    <% if user_signed_in? %>
      <% if current_user.website.present? %>
        <% if current_user.website.url.present? %>
          <li><%= link_to 'Éditer mon site', edit_own_website_url(host: current_user.website.host), class: 'link' %></li>
        <% else %>
          <li><%= link_to 'Éditer mon site', edit_website_url(current_user.website), class: 'link' %></li>
        <% end %>
      <% else %>
        <li><%= link_to 'Créer mon site', websites_path, method: :post, class: 'link' %></li>
      <% end %>
      <li><%= link_to 'Me déconnecter', destroy_user_session_path, class: 'link', method: :delete %></li>
    <% else %>
      <li><%= link_to 'Me connecter', new_user_session_path, class: 'link' %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_panel.html.erb
<% twitter_link = "https://twitter.com/home?status=Take%20a%20look%20at%20the%20website%20I%20made%20with%20Hop%3A%20#{root_url}#{@website.url}%20%23HopYourWebsite" %>
<% facebook_link = "https://www.facebook.com/sharer/sharer.php?u=#{root_url}#{@website.url}" %>

<div class="panel">
  <%= simple_form_for @website, url: @url, remote: true, html: { class: 'template-form' } do |f| %>
  <!--display name by default -->
  <div id="style-inputs">
    <h3>Choisissez l'apparence de votre site</h3>
    <p>Essayez les différent thèmes et <span>trouvez celui qui vous correspond le mieux</span>.</p>
    <%= f.input :template_id, label: false do %>
      <%= f.collection_radio_buttons :template_id, @templates, :id, :name, item_wrapper_tag: :span, item_wrapper_class: :radio do |b| %>
        <%= b.radio_button(data: { template: asset_path("layouts/#{b.object.slug}.css") }) %> <%= b.object.name.capitalize %>
      <% end %>
    <% end %>

    <%= f.input :color_id, label: false, collection: { asset_path("layouts/green.css") => 'Vert', asset_path("layouts/blue.css") => 'Bleu', asset_path("layouts/red.css") => 'Rouge' }, value_method: :first, label_method: :last,  as: :radio_buttons %>
  </div>

  <div class="edit-banner">

  </div>

  <div id="edit-inputs">
    <%= f.input :banner_title, placeholder: "Mon beau gîte" %>
    <%= f.input :banner_punchline, as: :text, placeholder: 'Gîte accueillant dans un cadre magnifique' %>
    <%= f.input :banner_background, as: :attachinary, cloudinary: { transformation: {opacity: 50}} %>
    <h3>Saisissez votre contenu</h3>
    <p>Remplissez les champs pour <span>compléter votre site web</span>.</p>
    <%= f.input :title, placeholder: "Bienvenue en vacances" %>
    <%= f.input :description, as: :text, placeholder: 'Venez passez vos vacances dans un cadre exceptionnel.', input_html: {rows: 10} %>
    <%= f.input :background_image, as: :attachinary, cloudinary: { transformation: {opacity: 50}} %>
    <%= f.input :profile_image, as: :attachinary %>
    <%= f.input :facebook_url, placeholder: 'monbeaugite', label: 'Nom de la page Facebook' %>
    <p>Ceci correspond à ce qui est après <span>https://facebook.com/</span> dans l'URL de votre page.</p>
    <%= f.input :twitter_url, placeholder: '@monbeaugite', label: 'Nom du compte  Twitter' %>
    <p>Ajoutez votre <span>@nom</span> Twitter.</p>
    <%= f.input :email, placeholder: 'gite@riberac-tourisme.com' %>
  </div>

  <div id="publish-inputs">
    <h3>Choisissez votre URL</h3>
    <p>Cette URL apparaîtra au format<br/>http://<span>mon-beau-gite</span>.<%= ENV['APPLICATION_DOMAIN'] %>.</p>
    <%= f.input :url, label: false, placeholder: 'mon-beau-gite' %>
  </div>

  <%= f.button :submit, class: 'button btn-block', id: 'website-submit', value: 'Selectionnez le thème' %>

  <% end %>

  <div class="result">
    <p>Bien joué, votre site est <span>en ligne</span>! Partagez le sur les réseaux sociaux.</p>
    <%= link_to 'Voir votre site', '#', target: '_blank', class: 'link button' %>
    <%= link_to facebook_link, target: '_blank', class: 'link button facebook-link' do %>
    <i class="fa fa-facebook" aria-hidden="true"></i> Partager sur Facebook
    <% end %>
    <%= link_to twitter_link, target: '_blank', class: 'link button twitter-link' do %>
    <i class="fa fa-twitter" aria-hidden="true"></i> Partager sur Twitter
    <% end %>
  </div>
</div>

app/views/shared/_process.html.erb
<script>
  let intervalID
  function changeCouleur() {
    intervalID = setInterval(changeLogo, 1000);
  }
  function changeLogo() {
    let elem = document.getElementById("logo-style");
    let elm = document.getElementById("logo-edit");

    if (elem.src == "<%= image_url 'cube-style-black.png' %>" ) {
      elem.src = "<%= image_url 'cube-style-primary.png' %>"  ;
    } else if (elem.src == "<%= image_url 'cube-style-primary.png' %>") {
      elem.src = "<%= image_url 'cube-style-secondary.png' %>" ;
    } else {
      elem.src = "<%= image_url 'cube-style-black.png' %>";
    }
  }

  function stopTextColor() {
  clearInterval(intervalID);
  }
</script>

<div class="container process-title">
  <h2>Comment ça marche?</h2>
</div>

<div class="process-wrapper">
  <div class="container">
    <div class="process-section">
      <div class="row">
        <div class="col-sm-6 col-md-3">
          <div class="process-card">
            <p class="step">1</p>
            <%= link_to image_tag("cube-style-black.png", class: "process-logo-resize", id: "logo-style"), websites_path, method: :post %>
            <h3>Personnalisez l'apparence</h3>
            <%= image_tag "arrow-primary.png", class: 'process-card-arrow hidden-xs' %>
          </div>
        </div>

        <div class="col-sm-6 col-md-3">
          <div class="process-card">
            <p class="step">2</p>
            <%= image_tag "cube-edit.png", class: 'process-logo-resize' %>
            <h3>Remplissez le contenu</h3>
            <%= image_tag "arrow-primary.png", class: 'process-card-arrow hidden-xs' %>
          </div>
        </div>

        <div class="col-sm-6 col-md-3">
          <div class="process-card">
            <p class="step">3</p>
            <%= image_tag "cube-url.png", class: 'process-logo-resize' %>
            <h3>Choisissez l'adresse</h3>
            <%= image_tag "arrow-primary.png", class: 'process-card-arrow hidden-xs' %>
          </div>
        </div>

        <div class="col-sm-6 col-md-3">
          <div class="process-card">
            <p class="step">4</p>
            <%= image_tag "cube-website.png", class: 'process-logo-resize' %>
            <h3>Partagez votre site web !</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_toolbar.html.erb
<div class="toolbar">
  <%= link_to root_path, class: 'home-button' do %>
  <i class="fa fa-angle-left fa-2x" aria-hidden="true"></i>
  <% end %>
  <ul class="toolbar-menu">
    <li class="toolbar-menu-item toolbar-menu-item-active"><%= link_to 'Style', '#' %></li>
    <span>&gt;</span>
    <li class="toolbar-menu-item"><%= link_to 'Edit', '#' %></li>
    <span>&gt;</span>
    <li class="toolbar-menu-item"><%= link_to 'Publish', '#' %></li>
  </ul>
  <%= link_to '#', class: 'mobile-button hidden-xs' do %>
    <i class="fa fa-mobile fa-2x" aria-hidden="true"></i>
  <% end %>
</div>

app/views/templates/_template.html.erb
<div class="template-flex" style="back">

    <%= link_to "https://github.com/dhh", target: :_blank do %>
      <%= image_tag 'Profile_Valentin.jpg', class: 'template-photo'%>
    <% end %>

  <div class="template-title">
    <h1>Hi ! I'm a master developper 💻</h1>
  </div>

  <div class="template-description">
    <p>Websites did not need to be big, elaborate, and flashy. They just needed to get the point across, and that is exactly the purpose they served.</p>
    <p>In 1994 the World Wide Web Consortim or W3C was established to oversee the development of web technology standards. The W3C designated HTML as the primary code language for the future of website design to be based on. Of course they have made advancements in the base design code such as HTML versions one, two, three, four, and XHTML. </p>
  </div>

  <div class="template-network">
    <%= link_to "#", target: :_blank do %>
      <i class="fa fa-facebook-official fa-2x icon-color" aria-hidden="true"></i>
    <% end %>
    <%= link_to "#", target: :_blank do %>
      <i class="fa fa-envelope-o fa-2x icon-color" aria-hidden="true"></i>
    <% end %>
    <%= link_to "#", target: :_blank do %>
      <i class="fa fa-twitter-square fa-2x icon-color" aria-hidden="true"></i>
    <% end %>
  </div>
</div>

app/views/templates/_template_east.html.erb
<div class="template-container template-east" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.4)), url('<%= cl_image_path_or_default @website.background_image %>');" >

  <div class="content">
    <%= cl_image_tag_or_default(@website.profile_image, class: 'template-photo') %>
    <h1 class="title-clicked"><%= @website.title %></h1>

    <p class="description-clicked"><%= @website.description %></p>

    <div class="links">
      <% if (!@website.email.empty? )%>
        <%= link_to 'Contact', "mailto:#{@website.email}", target: :_blank, class: 'contact' %>
      <% end %>

      <% if (!@website.facebook_url.empty?)%>
        <%= link_to "https://facebook.com/#{@website.facebook_url}", target: :_blank do %>
          <i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i>
        <% end %>
      <% end %>

      <% if (!@website.twitter_url.empty? )%>
        <%= link_to "https://twitter.com/#{@website.twitter_url}", target: :_blank do %>
        <i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/templates/_template_north.html.erb
<div class="template-container template-north" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.4)), url('<%= cl_image_path_or_default @website.background_image %>');" >

  <div class="content">
    <h1 class="title-clicked"><%= @website.title %></h1>

    <p class="description-clicked"><%= @website.description %></p>

    <div>
      <% if (!@website.facebook_url.empty?)%>
        <%= link_to "https://facebook.com/#{@website.facebook_url}", target: :_blank do %>
          <i class="fa fa-facebook" aria-hidden="true"></i>
        <% end %>
      <% end %>

      <% if (!@website.twitter_url.empty? )%>
        <%= link_to "https://twitter.com/#{@website.twitter_url}", target: :_blank do %>
        <i class="fa fa-twitter" aria-hidden="true"></i>
        <% end %>
      <% end %>

      <% if (!@website.email.empty? )%>
        <%= link_to "mailto:#{@website.email}", target: :_blank do %>
          <i class="fa fa-envelope-o" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/templates/_template_south.html.erb
<div class="template-container" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.4)), url('<%= cl_image_path_or_default @website.background_image %>');" >
  <div class="template-south">
    <div class="template-south h1">
      <h1 class="title-clicked"><%= @website.title %></h1>
    </div>
    <div class="template-south p">
      <p class="description-clicked"><%= @website.description %></p>
    </div>
    <div class="template-south-links">
      <% if (!@website.facebook_url.empty?)%>
        <%= link_to "https://facebook.com/#{@website.facebook_url}", target: :_blank do %>
          <i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i>
        <% end %>
      <% end %>
      <% if (!@website.twitter_url.empty? )%>
        <%= link_to "https://twitter.com/#{@website.twitter_url}", target: :_blank do %>
          <i class="fa fa-twitter-square fa-2x" aria-hidden="true"></i>
        <% end %>
      <% end %>
      <% if (!@website.email.empty? )%>
        <%= link_to "mailto:#{@website.email}", target: :_blank do %>
          <i class="fa fa-envelope-o fa-2x" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/templates/_template_west.html.erb
<div class="template-container template-west" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.4)), url('<%= cl_image_path_or_default @website.background_image %>');" >

  <div class="container-half">
    <div class="losange">
      <div class="losange-img">
      </div>
    </div>

    <div class="box">
      <h1 class="title-clicked"><%= @website.title %></h1>
      <p class="description-clicked"><%= @website.description %></p>
    </div>

    <div class="social">
          <% if (!@website.facebook_url.empty?)%>
            <%= link_to "https://facebook.com/#{@website.facebook_url}", target: :_blank do %>
              <i class="fa fa-facebook" aria-hidden="true"></i>
            <% end %>
          <% end %>

          <% if (!@website.twitter_url.empty?)%>
            <%= link_to "https://twitter.com/#{@website.twitter_url}", target: :_blank do %>
              <i class="fa fa-twitter" aria-hidden="true"></i>
            <% end %>
          <% end %>

          <% if (!@website.email.empty?)%>
            <%= link_to "mailto:#{@website.email}", target: :_blank do %>
              <i class="fa fa-envelope-o" aria-hidden="true"></i>
            <% end %>
          <% end %>
    </div>
  </div>
</div>

app/views/tooltips/_tooltip_navigate.html.erb
<div class="tooltip-container tooltip-navigate">
  <div class="tooltip-content">
    <div class="tooltip-head">
      <div class="tootip-title">Suivez les étapes</div>
      <span class="cross-icon">&#10005;</span>
    </div>
    <div class="tooltip-text">Utilisez le panneau de droite pour construire votre site. Si vous êtes perdus, la barre en bas de la page vous indique l'étape sur laquelle vous vous trouvez.</div>
  </div>
</div>

app/views/tooltips/_tooltip_welcome.html.erb
<div class="tooltip-container tooltip-welcome">
  <div class="tooltip-content">
    <div class="tooltip-head">
      <div class="tootip-title">Bienvenue sur votre nouveau site Web</div>
      <span class="cross-icon">&#10005;</span>
    </div>
    <div class="tooltip-text">Choisissez comment organiser votre page, son thème de couleur, son nom de domaine et créez votre site en quelques minutes !</div>
  </div>
</div>

app/views/websites/index.html.erb
<% title("My dashboard") %>

<div class="websites-wrapper">
  <%= render 'shared/navbar' %>
  <div class="container">
    <div class="websites-list">
      <h1>My websites</h1>
      <div class="row">
        <% @websites.each do |website| %>
        <div class="col-sm-4">
          <div class="website">
            <h2><%= website.title %></h2>
            <ul class="list-inline list-unstyled">
              <li>
                <%= link_to "#{root_path}#{website.url}", target: '_blank' do %>
                  <i class="fa fa-eye" aria-hidden="true"></i>
                <% end %>
              </li>
              <li>
                <%= link_to edit_website_path(website) do %>
                  <i class="fa fa-pencil" aria-hidden="true"></i>
                <% end %>
              </li>
              <!-- <li>
                <%= link_to '#' do %>
                  <i class="fa fa-trash-o" aria-hidden="true"></i>
                <% end %>
              </li> -->
            </ul>
          </div>
        </div>
        <% end %>
        <div class="col-sm-4">
          <%= button_to 'Create new', websites_path, class: 'website button' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/websites/show.html.erb
<% title @website.title %>

<div class="website-template-container">
  <div class='flex-container'>
    <%= render "website_components/banner", website: @website %>
    <%= render "templates/template_west" %>
  </div>
  <%= render "website_components/team" %>
</div>